### ISSUE TITLE
Doesn't clean up the inject after loading/writing a save

### ISSUE THREAD

**Issue by parkerlreed** [d3m3vilurr/vita-savemgr#39] opened 2017-03-27 21:33 UTC
PSTV 3.60

uma0 as ux0 with Vitashell

Latest vita-savemgr

I have Need for Speed: Hot Pursuit as a cartridge (with digital update)

I went in and selected the game, the inject worked correctly, it auto launches the inject and then I load a save. I press Circle a few times to back out and exit vita-savemgr. This leaves the ux0:patch/TITLEID_orig and ux0:patch/TITLEID (injected) folders without restoring the orig. I manually deleted the inject and renamed the orig back to normal and everything is working.

EDIT: Just noticed it did the same on my regular Vita. (Where I only did a save) Had to remove the injected folder and rename there too.

**Comment by FinalDoom** [comment] 2017-04-27 22:05
Confirmed, this is a regression on the nighly version compared to 0.8.0, in which it works correctly.

**Comment by d3m3vilurr** [comment] 2017-05-04 11:43
@FinalDoom you mean 0.8.0 was work, but broken nightly?

**Comment by FinalDoom** [comment] 2017-05-20 13:49
@d3m3vilurr sorry I guess I don't get notifications anywhere I read.

Correct, 0.8.0 works correctly (remove injected files and restore original game) and the nightly does not.

**Comment by d3m3vilurr** [comment] 2017-06-10 09:12
Sorry too late.
I don't have hot pursuit, but at least I try cartridge version most wanted and works in my test.
So, I need your device setting, for example, extra plugins.

Close this issue until getting more detail information.

**Closed by d3m3vilurr** 2017-06-10 09:12 UTC

**Comment by DuIslingr** [comment] 2017-06-10 16:47
Occurs with my Persona 4 Golden cartridge as well. This only applies to the nightly. as was stated v0.8 works correctly. PSTV henkaku/taihenkaku any version. Only other plugin i have is the overclocking one which is irrelevant since it occurred before I installed it.

**Comment by d3m3vilurr** [comment] 2017-06-10 16:56
@DuIslingr only problem in pstv? and I need info w/o any extra plugins.

**Comment by DuIslingr** [comment] 2017-06-11 18:20
I specifically said even without plugins it still occurs and i only have a pstv to test with.

**Comment by FinalDoom** [comment] 2017-06-12 18:02
I'm on a PCSH1104 (3g wifi), cart version of DOAX3, no plugins. I haven't played a non-cartridge in a while, but I can give it a try with one if that'd help.

**Comment by MarioMasta64** [comment] 2017-10-22 21:46
i had the same problem with psvita PCH-2000 (WIFI) w/i plugins when trying danganronpa 2 PCSE00399 the folder isnt deleted properly and i have to manually delete it.

**Comment by FinalDoom** [comment] 2017-11-22 05:11
I haven't gone back to try it on my Vita, but I think I discovered the problem/solution through my psTV. A fresh install of the Save Manager works fine, as it used to, with the newest version. However, I was having the above problem when updating from 0.8.0 to the nightly. I believe that the failure point is probably some files stored by 0.8.0 that confuse the nightly, such as the now removed sce(? it's been a while) account files that the nightly now omits automatically. Some day I'll go back and clean up my Vita and do troubleshooting.

Short story:
Solution is (should be anyway) to uninstall the app and remove all your saves/settings for it (rename the saves folder, eg.) then reinstall the nightly and it should work fine.
